apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jktlug-website
  namespace: jktlug
  labels:
    app.kubernetes.io/name: jktlug-website
    app.kubernetes.io/instance: production
spec:
  ingressClassName: traefik

  rules:
    - host: jktlug.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jktlug-website
                port:
                  number: 80

    - host: www.jktlug.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jktlug-website
                port:
                  number: 80