apiVersion: v1
kind: Service
metadata:
  name: jktlug-website
  namespace: jktlug-dev
  labels:
    app.kubernetes.io/name: jktlug-website
    app.kubernetes.io/instance: dev
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: jktlug-website
    app.kubernetes.io/instance: dev
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
